language: scala
scala:
   - 2.12.1
   - 2.11.9
jdk: oraclejdk8
script:
  - sbt clean coverage "testOnly -- showtimes true timeFactor 5 exclude no-ci"
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
   - ~/.ivy2
   - ~/.sbt
